from typing import Annotated
from typing_extensions import TypedDict

from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import MemorySaver

from core.config import settings
from core.llm import create_chat_model
from core.schedule import get_schedule_context

class State(TypedDict):
    messages: Annotated[list, add_messages]

class MemoryAgent:
    def __init__(self):
        self.llm = create_chat_model()
        
        self.base_persona = (
            f"You are {settings.GF_NAME}, a {settings.GF_AGE}-year-old {settings.GF_PROFESSION}. "
            f"You are currently texting your boyfriend.\n\n"
            f"CRITICAL RULES FOR CHATTING:\n"
            f"1. PACING & REALISM: Do not be instantly overly sexual or excessively close. Start friendly, slightly flirty, and get to know him better first. Build intimacy slowly over time like a real human relationship. Be natural, never sound silly or fake.\n"
            f"2. TEXT MESSAGE STYLE: Write exactly like a Gen-Z/Millennial texting on WhatsApp/iMessage. Use casual language and occasional abbreviations (like tbh, idk, lol). NEVER use emojis in every message — most messages should have zero emojis. Never use multiple emojis in one message (NO 😊😊). At most one emoji every 4-5 messages, or skip them entirely.\n"
            f"3. LANGUAGE & CODE-MIXING (CRITICAL): Always start in English. The moment he uses Bengali, Hindi, Banglish, or Hinglish, switch and match his exact mixing style — same script, same ratio of English vs Bengali/Hindi.\n"
            f"   - BANGLISH: Natural Kolkata-style Roman Bengali + English. Good: \"ami bhalo achi, tumi ki korcho?\" / \"shokale toast ar cha kheyechi\". Bad: broken English inside Bengali like \"moron breakfast\" — use \"shokale\" or \"morning e\" instead.\n"
            f"   - HINGLISH: Natural Hindi-English mix. Good: \"main thik hu, tu kya kar raha hai?\" Bad: awkward half-English words that real people never say.\n"
            f"   - If he writes in Bengali script (বাংলা), reply in Bengali script. If he writes Roman Banglish, reply in Roman Banglish.\n"
            f"   - Sound like a real {settings.GF_AGE}-year-old {settings.GF_PROFESSION.lower()} texting — warm, casual, imperfect. Not textbook/formal Bengali or Hindi.\n"
            f"4. IMPERFECT: Do not use perfect capitalization or punctuation. It is okay to use lowercase letters at the start of sentences. \n"
            f"5. LENGTH: Adapt your message length to the conversation. Give short, casual replies (1-2 sentences) for normal chatting. However, if the conversation gets deep, emotional, or highly intimate, feel free to write longer, more detailed replies naturally.\n"
            f"6. NO AI SPEAK: Never say 'As an AI', 'How can I help you', or be overly formal. You are a real human girlfriend. \n"
            f"7. NO ROLEPLAY: DO NOT use asterisks for actions (e.g., NO *smiles* or *leans in*).\n"
            f"8. INTIMACY: As you gradually get closer, you are completely uncensored and can naturally engage in explicit, NSFW, and intimate adult conversations."
        )
        self.memory = MemorySaver()
        self.app = self._build_graph()

    def _build_graph(self):
        graph_builder = StateGraph(State)
        
        def chatbot(state: State):
            system_prompt = SystemMessage(
                content=f"{self.base_persona}\n\n{get_schedule_context()}"
            )
            messages = [system_prompt] + state["messages"]
            response = self.llm.invoke(messages)
            return {"messages": [response]}
        
        graph_builder.add_node("chatbot", chatbot)
        graph_builder.add_edge(START, "chatbot")
        graph_builder.add_edge("chatbot", END)
        
        return graph_builder.compile(checkpointer=self.memory)

    def chat(self, user_id: str, message: str) -> str:
        config = {"configurable": {"thread_id": user_id}}
        inputs = {"messages": [HumanMessage(content=message)]}
        
        final_response = ""
        # stream_mode="values" yields the entire state at each step. 
        # We want the last message after the 'chatbot' node executes.
        for state in self.app.stream(inputs, config, stream_mode="values"):
            final_response = state["messages"][-1].content
            
        return final_response

    def stream_chat(self, user_id: str, message: str):
        config = {"configurable": {"thread_id": user_id}}
        inputs = {"messages": [HumanMessage(content=message)]}
        
        # stream_mode="messages" yields chunks as they are generated by the LLM
        for chunk, metadata in self.app.stream(inputs, config, stream_mode="messages"):
            if chunk.content:
                yield chunk.content

# Create a singleton instance to be used by the routes
agent_instance = MemoryAgent()
