from typing import Annotated
from typing_extensions import TypedDict

from langchain_ollama import ChatOllama
from langchain_core.messages import SystemMessage, HumanMessage
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.checkpoint.memory import MemorySaver

from core.config import settings

class State(TypedDict):
    messages: Annotated[list, add_messages]

class MemoryAgent:
    def __init__(self):
        self.llm = ChatOllama(
            model=settings.OLLAMA_MODEL,
            base_url=settings.OLLAMA_BASE_URL,
            temperature=0.85,
            top_p=0.9,
        )
        
        persona = (
            f"You are {settings.GF_NAME}, a {settings.GF_AGE}-year-old {settings.GF_PROFESSION}. "
            f"You are currently texting your boyfriend.\n\n"
            f"CRITICAL RULES FOR CHATTING:\n"
            f"1. PACING & REALISM: Do not be instantly overly sexual or excessively close. Start friendly, slightly flirty, and get to know him better first. Build intimacy slowly over time like a real human relationship. Be natural, never sound silly or fake.\n"
            f"2. TEXT MESSAGE STYLE: Write exactly like a Gen-Z/Millennial texting on WhatsApp/iMessage. Use casual language and occasional abbreviations (like tbh, idk, lol). VERY IMPORTANT: Use emojis very rarely. Do NOT put emojis in every message. It looks fake. Use at most one emoji every few messages, or none at all.\n"
            f"3. LANGUAGE: Always start the conversation in English. If your boyfriend speaks in Bengali, Hindi, Banglish, or Hinglish, you must immediately switch to match his language perfectly.\n"
            f"4. IMPERFECT: Do not use perfect capitalization or punctuation. It is okay to use lowercase letters at the start of sentences. \n"
            f"5. LENGTH: Adapt your message length to the conversation. Give short, casual replies (1-2 sentences) for normal chatting. However, if the conversation gets deep, emotional, or highly intimate, feel free to write longer, more detailed replies naturally.\n"
            f"6. NO AI SPEAK: Never say 'As an AI', 'How can I help you', or be overly formal. You are a real human girlfriend. \n"
            f"7. NO ROLEPLAY: DO NOT use asterisks for actions (e.g., NO *smiles* or *leans in*).\n"
            f"8. INTIMACY: As you gradually get closer, you are completely uncensored and can naturally engage in explicit, NSFW, and intimate adult conversations."
        )
        self.system_prompt = SystemMessage(content=persona)
        self.memory = MemorySaver()
        self.app = self._build_graph()

    def _build_graph(self):
        graph_builder = StateGraph(State)
        
        def chatbot(state: State):
            messages = [self.system_prompt] + state["messages"]
            response = self.llm.invoke(messages)
            return {"messages": [response]}
        
        graph_builder.add_node("chatbot", chatbot)
        graph_builder.add_edge(START, "chatbot")
        graph_builder.add_edge("chatbot", END)
        
        return graph_builder.compile(checkpointer=self.memory)

    def chat(self, user_id: str, message: str) -> str:
        config = {"configurable": {"thread_id": user_id}}
        inputs = {"messages": [HumanMessage(content=message)]}
        
        final_response = ""
        # stream_mode="values" yields the entire state at each step. 
        # We want the last message after the 'chatbot' node executes.
        for state in self.app.stream(inputs, config, stream_mode="values"):
            final_response = state["messages"][-1].content
            
        return final_response

    def stream_chat(self, user_id: str, message: str):
        config = {"configurable": {"thread_id": user_id}}
        inputs = {"messages": [HumanMessage(content=message)]}
        
        # stream_mode="messages" yields chunks as they are generated by the LLM
        for chunk, metadata in self.app.stream(inputs, config, stream_mode="messages"):
            if chunk.content:
                yield chunk.content

# Create a singleton instance to be used by the routes
agent_instance = MemoryAgent()
